branches:
    only:
        - master

language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8

compiler:
    - g++

before_install:
    - sudo apt-get install -y libffi-dev
    - export PYTHONPATH=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
    - mkdir $HOME/lib
    - mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION
    - mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages

cache:
    pip: true
    directories:
    - $HOME/fitsio

install:
    - pip install -r requirements.txt
    - pip install nose codecov

script:
    - echo PF ICI
    - echo $HOME
    - echo $TRAVIS_PYTHON_VERSION
    - echo $PYTHONPATH
    - python setup.py install --prefix=$HOME
    - cd tests
    - nosetests --with-coverage --cover-package=treegp

after_success:
    - codecov