name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment
        run: |
          sudo apt-get install -y libffi-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest-codecov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install treegp
        run: |
          python setup.py install

      - name: Test with pytest and submit to codecov
        run: |
          cd tests
          pytest --codecov
      - name: Report coverage
        run: |
          coverage report
